### ISSUE TITLE
Feed not working

### ISSUE THREAD

**Issue by OzzyCzech** [yarnpkg/website#1101]
Hi there,

rss feed not working, there is template but server returns 404 page not found

https://yarnpkg.com/feed.xml

**Comment by Haroenv** [comment]
Hey @OzzyCzech, the feed here was posted for https://classic.yarnpkg.com/feed.xml (which still worked), but since the new site doesn't have a feed, it's best to delete the one here: https://github.com/yarnpkg/website/commit/390d8595c1d7f3991cec0ddb7ae3f1ec3f143546

If you want a feed for the new blog, please open an issue on yarnpkg/berry

Thanks!
