### ISSUE TITLE
Document .yarnrc, how to use @scoped private packages, how to configure multiple registries

### ISSUE THREAD

**Issue by shakefu** [yarnpkg/website#132]
Docs are super sparse/non-existent on how to use yarn with the above.

Moved from yarnpkg/yarn#689.

**Comment by roryokane** [comment]
“[Configuration](https://yarnpkg.com/en/docs/configuration)” and “[`yarn config`](https://yarnpkg.com/en/docs/cli/config)” are the existing pages that I would expect to mention the `.yarnrc`, but don’t. We also need a list of the allowed `yarn config set` keys and their meanings on at least one of those pages.

**Comment by jakubzitny** [comment]
This issue is mentioning the documentation only and from https://github.com/yarnpkg/yarn/issues/521 it looks like privately scoped packages and also private registries do work. I was not able to make it work / it is not clear whether a combination of multiple registries works. Does it?

**Comment by gforceg** [comment]
As of right now it appears that yarn piggy backs on the npm configuration (.npmrc).

So after setting up [my scoped package registry](https://www.visualstudio.com/en-us/docs/package/npm/scopes) in .npmrc, [and using environmental variables rather than yarn / npm config variables for proxy settings](https://github.com/npm/npm/issues/7168)

`yarn add @myscope/mypackage` and `yarn info @myscope/mypackage` "just works" which is great because [npm works poorly under windows currently](https://github.com/npm/npm/issues/17671). Yarn really saved my bacon!

**Comment by shakefu** [comment]
This probably isn't relevant anymore.
