### ISSUE TITLE
Brew install name conflict with Hadoop Yarn

### ISSUE THREAD

**Issue by jspooner** [yarnpkg/website#326]
The macOS install directions found [here](https://yarnpkg.com/en/docs/install#mac-tab) fail if you have Apache Hadoop installed.

**Comment by Haroenv** [comment]
```sh
$ brew info yarn
yarn: stable 0.21.3 (bottled), HEAD
JavaScript package manager
https://yarnpkg.com/
/usr/local/Cellar/yarn/0.20.0 (4,760 files, 18.1MB) *
  Poured from bottle on 2017-02-06 at 13:50:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb
==> Dependencies
Required: node ✘
```

I think this has been fixed since.

**Comment by Haroenv** [comment]
Feel free to reopen if you still have this issue

**Comment by MGloder** [comment]
brew info yarn                                                                                ✔  1108  17:00:13

yarn: stable 1.10.1
JavaScript package manager
https://yarnpkg.com/
Conflicts with:
  hadoop (because both install `yarn` binaries)
/usr/local/Cellar/yarn/1.9.2 (14 files, 4.2MB)
  Built from source on 2018-08-03 at 11:16:37
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb
==> Dependencies
Recommended: node ✘
==> Options
--without-node
	Build without node support
==> Analytics
install: 105,000 (30d), 337,782 (90d), 1,016,859 (365d)
install_on_request: 103,746 (30d), 331,116 (90d), 984,888 (365d)
build_error: 0 (30d)

**Comment by jazzyfresh** [comment]
ongoing discussion in https://github.com/yarnpkg/yarn/issues/2337
