### ISSUE TITLE
Update npm vs yarn comparison

### ISSUE THREAD

**Issue by thomaschaaf** [yarnpkg/website#372]
Hello,

I'd like to try to update the https://yarnpkg.com/compare/ page. What repository was used so that I can do an up to date comparison?

Thomas

**Comment by thejameskyle** [comment]
I actually have a server written to automatically run performance tests and update the repo each night. But I've never been able to get it fully setup.

I'm afraid I can't make the code public either because of legal restrictions at Fb.

**Comment by thomaschaaf** [comment]
Could we use another big repository which is open source and then we could use travis / circleci to do daily runs with the latest stable and upcoming npm yarn version. Maybe someone has a suggestion which project would be a good fit.

**Comment by thejameskyle** [comment]
Here's the code: https://github.com/yarnpkg/perf

**Comment by thomaschaaf** [comment]
:( https://github.com/thomaschaaf/npm-vs-yarn I just built my own and chose ghost and react. Now I just have to send it somewhere and chart it. It get's run by travis every day and I want to display the average for each npm/yarn version.

**Comment by thomaschaaf** [comment]
I have continued the development and am now sending the data to https://docs.google.com/spreadsheets/d/1ZE5B4qJw1kNGMzjgslcWTuPYrpatzQJXSYMGNOhZ2ys/edit?usp=sharing on the bottom you can switch "tables" - between "Dashboard", "Pivot" and "Data". As soon as I have a little data I will add some pretty graphs to the dashboard :)

**Comment by kripod** [comment]
Could you please make a comparison between yarn@0.24 and npm@5? I'm very curious about the improvements npm@5 has brought.

**Comment by zkat** [comment]
tbh, this webpage is tremendously out of date. It would be really kind of y'all to rerun these benchmarks, because this is really misguiding right now. I would also recommend adding pnpm, since they're definitely active and doing a lot of decent work recently (and getting noticed for it).

### Warm cache, 2015 MBP, lockfiles

<img width="321" alt="screen shot 2017-07-13 at 22 40 52" src="https://user-images.githubusercontent.com/17535/28199979-3df0e2f2-681e-11e7-8726-be2cf8dfd492.png">
<img width="327" alt="screen shot 2017-07-13 at 22 56 41" src="https://user-images.githubusercontent.com/17535/28200056-92feab94-681e-11e7-9b71-8c0e8ee854e1.png">

### Cold cache, 2015 MBP, lockfiles

<img width="322" alt="screen shot 2017-07-13 at 22 52 45" src="https://user-images.githubusercontent.com/17535/28200025-6d207704-681e-11e7-9481-3d5d36a7b4d4.png">
<img width="338" alt="screen shot 2017-07-13 at 22 52 31" src="https://user-images.githubusercontent.com/17535/28200029-702408e4-681e-11e7-8006-484bdfb0a68d.png">

**Comment by Haroenv** [comment]
@thejameskyle, is the data that’s now on the site created with yarnpkg/perf?
