### ISSUE TITLE
Angular Material Package Detail

### ISSUE THREAD

**Issue by fybwid** [yarnpkg/website#590]
In the package detail, the url pointing to Angular Material repository is incomplete,
`[main AngularJS Material repository](https://github.com/angular/materi`
which is should be:
`[main AngularJS Material repository](https://github.com/angular/material)`

**Comment by Haroenv** [comment]
Hey, thanks for opening this issue, unfortunately this is out of our control because the registry truncates the description at that length. You can change that for Angular Material themselves by saving some characters in the description field of their package.json so that the link would work. 

see data here: https://registry.yarnpkg.com/angular-material

Have a nice day!

**Comment by fybwid** [comment]
Hey, thanks for your explanation.
You said "the registry truncates the description at that length" so what is the maximum length of the character?

**Comment by Haroenv** [comment]
```js
"This repository is used only for AngularJS Material v1.x library deployments and localized installs using `npm` and `bower`. The actual component source-code for this library is in the [main AngularJS Material repository](https://github.com/angular/materi".length;
```

It's 255 characters

**Comment by fybwid** [comment]
@Haroenv Thanks for your explanation.
