### ISSUE TITLE
Unpublish

### ISSUE THREAD

**Issue by peteringram0** [yarnpkg/website#600]
With npm there is a npm unpublish command but this does not seem to exist with yarn. My package has been removed from NPM but yarn has a cache. How can i get rid of this cache please? 

Thanks

**Comment by Haroenv** [comment]
Hey, for now the README and its metadata will indeed still be visible from the Yarn website, even though it’s unpublished and not installable. 

For now an email to haroen@algolia.com will be sufficient to get it deleted rapidly. 

I’m closing this, since this is actually tracked in https://github.com/algolia/npm-search/issues/51
