### ISSUE TITLE
Docs: clearly document which versions of node are supported

### ISSUE THREAD

**Issue by BYK** [yarnpkg/website#646]
Came up in Discord and in some other issues.

Looks like as of 1.0 we support `^4.8.0` and `>= 5.7.0` and this should be clearly visible on the website, hopefully on the front-page.

**Comment by gargoyle** [comment]
Can the main yarn command be able to spit something out? In the last 6 months since switching `npm` for `yarn` I don't think I have been back to yarnpkg.com.

Additionally, even after seeing this closed issue, I still didn't see the dependency at first. The problem being a subtle UX one - after the homepage, I mentally blocked out the big blue section at the top as "page header".

You should move or repeat it in the main content. Preferably in some kind of "Hey, this is important" styling.

**Comment by BYK** [comment]
>Can the main yarn command be able to spit something out? 

I think this is not a bad idea. We can have a more specific engines field in Yarn and then check this at every invocation. It may be a bit costly though.

**Comment by BYK** [comment]
>You should move or repeat it in the main content. Preferably in some kind of "Hey, this is important" styling.

I think this is already done but the site didn't deploy after the PR. Ping @Haroenv for that.

**Comment by gargoyle** [comment]
I've also just submitted another PR to get rid of the paragraph below the first section which says you don't need nodesource for 16.04 - because it seems you do.

https://github.com/yarnpkg/website/pull/652

Sorry I can't do more, not really familiar with the tooling yo are using for the website / docs. (I'm not actually a front-end dev). I just have to make sure the dev VM keeps working! :-)

**Comment by BYK** [comment]
>Sorry I can't do more, not really familiar with the tooling yo are using for the website / docs. (I'm not actually a front-end dev). I just have to make sure the dev VM keeps working! :-)

Hahaha, no worries, you already helped a lot. Thanks!

**Comment by Haroenv** [comment]
Let's take a look at this deploy issue tomorrow. I thought I fixed it 😱

**Comment by BYK** [comment]
😢

**Comment by Daniel15** [comment]
> Can the main yarn command be able to spit something out? 

It does check, but only for Node <4: https://github.com/yarnpkg/yarn/blob/master/bin/yarn.js#L10-L12. We can likely make that check for a more specific version range.

**Comment by Haroenv** [comment]
Actually, no, it's visible on the website, builds worked since I fixed it @BYK. 

I'm going to close this, but you should probably reopen this issue on yarnpkg/yarn for making it clear in the cli

**Comment by BYK** [comment]
>Actually, no, it's visible on the website, builds worked since I fixed it @BYK.

Ah, I was expecting it on the homepage and it was on the installation page. I'll probably submit a PR to put it on the front-page too.

**Comment by Haroenv** [comment]
It can be on the homepage too I guess, I specifically made it an exception now, but you can simplify those two headers if that's preferred

**Comment by BYK** [comment]
I think it would be better to keep both version information visible at all times, especially on the landing page. What do you think?

**Comment by Haroenv** [comment]
Perfect, see #654
