### ISSUE TITLE
Recent update of install.sh breaks support for older OSX versions

### ISSUE THREAD

**Issue by Ivshti** [yarnpkg/website#647]
See this for background: https://github.com/yarnpkg/yarn/issues/1984

this commit introduces a new call to `mktemp` that's incompatible with older versions of OSX: https://github.com/yarnpkg/website/commit/fe7611b9e1d5e67401772521174d9ede3e2a80ab

This is a significant problem because a lot of Travis builds still use those OSX versions for legacy reasons (so that any binary builds would be backwards-compatible with older OSX versions)

**Comment by Ivshti** [comment]
This is a very easy fix. All it needs is a template given to `mktemp`, as mentioned in https://github.com/yarnpkg/yarn/issues/1984

**Comment by Daniel15** [comment]
Ugh, @BYK could you please take a look? I'm not going to have time to look at this since I'm flying to Australia tomorrow.

It's the `mktemp` thing again - It **requires** the template on old MacOS. Documented in the other issue that @Ivshti linked to.

I'd love to run our end-to-end tests on MacOS (like how we have end-to-end tests running on Ubuntu 12.04, 14.04 and 16.04), but unfortunately Apple don't officially allow you to virtualize MacOS on non-MacOS hardware. That means I can't run MacOS in a Docker container on my Linux system. 😢

**Comment by Daniel15** [comment]
Feel free to submit a PR fixing this, @Ivshti 😃

**Comment by Ivshti** [comment]
Done, but I don't have pre-sierra osx to test. I know that our travis builds fail because of this, but I haven't ran the updated version of the `install.sh` script. I assume it should work

Take a look: https://github.com/yarnpkg/website/pull/648

**Comment by Haroenv** [comment]
Seems like this can be closed now, thanks for your fast resolution @Ivshti 🎉

**Comment by Ivshti** [comment]
thanks for the merge, will this be uploaded to the site soon?

**Comment by Haroenv** [comment]
It's live. Earlier there was a bug in our CDN, but this should be the version you get if you clear the cache
