### ISSUE TITLE
Yarn install documentation recommending --frozen-lockfile for CI builds is too opinionated

### ISSUE THREAD

**Issue by Daniel15** [yarnpkg/website#700]
_From @sesopenko on October 31, 2017 16:9_

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
The top of the documentation page states that yarn install --frozen-lockfile is recommended for CI builds, failing a build if the lockfile is out of date.

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
Most organizations don't want to fail a build if the lockfile is out of date. This is too opinionated.  This recommendation should be removed, or present the options of --frozen-lockfile oir --pure-lockfile, explaining that --frozen-lockfile will fail the build if a remote dependency is updated (which is highly likely throughout any given day for a project with numerous dependencies)

It's recommended that the documentation be updated to suggest the options of --frozen-lockfile and --pure-lockfile, with an explanation of each.

**Please mention your node.js, yarn and operating system version.**
n/a:  documentation issue

_Copied from original issue: yarnpkg/yarn#4814_

**Comment by Daniel15** [comment]
_From @eventualbuddha on October 31, 2017 17:40_

FWIW, I think this recommendation is correct. If a lockfile is out of date with respect to the package.json, that's a problem and should not be allowed. If such a state is detected on a branch, that branch should not be merged. If your opinion is different, you're welcome to omit `--frozen-lockfile` or simply log and ignore the error.

**UPDATE**

> … explaining that --frozen-lockfile will fail the build if a remote dependency is updated

This seems to be the main reason for your objection, but I'm pretty sure this is not true. The whole point is that only changes to package.json should trigger changes to yarn.lock.

**Comment by Daniel15** [comment]
Moving to website repo as this issue relates to documentation. Thanks!

**Comment by Daniel15** [comment]
I want to get opinions from other Yarn devs (cc @yarnpkg/core), but I think @eventualbuddha is correct. The lock file won't suddenly become out-of-date through normal use. It'll only become out-of-date if someone modifies the `package.json` file without re-running Yarn. This will break the build, which is the correct behaviour. The package.json should never be out of sync with yarn.lock. Consequently, I don't see a reason to **not** use `--frozen-lockfile` on continuous builds.

**Comment by sesopenko** [comment]
Scenario: package.json has a remote dependency with a carat for the version
number, making it update to the latest minor symver.  Remote dependency
pushes a new minor version.

According to the documentation it will exit with a failure if
--frozen-lockfile is executed.

This is not helpful in a ci environment because it doesn't make sense to
fail a build due to a dependency being out of date. There's no real world
value to this in a ci/cd pipeline. In a ci/cd environment you install
what's exactly in the lock file because that's what is confirmed to be
passing in any integration tests.


On Oct 31, 2017 9:37 PM, "Daniel Lo Nigro" <notifications@github.com> wrote:

I want to get opinions from other Yarn devs (cc @yarnpkg/core
<https://github.com/orgs/yarnpkg/teams/core>), but I think @eventualbuddha
<https://github.com/eventualbuddha> is correct. The lock file won't
suddenly become out-of-date through normal use. It'll only become
out-of-date if someone modifies the package.json file without re-running
Yarn. This will break the build, which is the correct behaviour. The
package.json should never be out of sync with yarn.lock. Consequently, I
don't see a reason to *not* use --frozen-lockfile on continuous builds.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yarnpkg/website/issues/700#issuecomment-340969617>, or mute
the thread

**Comment by eventualbuddha** [comment]
I don’t have a completely firm grasp on exactly how yarn works because I have not read and understood all of the source code, but I believe the entire point of a system like yarn.lock (or package-lock.json, for that matter) is to lock down *all* dependencies, immediate or transitive. So it should not matter that one of your dependency `A` has a range dependency for `B` that would include a new release of `B`. The exact version (or versions, actually) of `B` are specified in the lock file and will not change simply because something happened in the outside world that created a new version of a package.

The only way the lock file should be updated when run is if you change the package.json associated with it (barring potential weird cases like a git merged yarn.lock file). Therefore, you absolutely do want `--frozen-lockfile` in CI because you don’t want your package.json and yarn.lock to get out of sync. In fact, I’ve been running it this way in CI at work on multiple highly active repositories for months now and it has never been a problem that a new version of a package has somehow invalidated our yarn.lock. Not once.

<hr>

As an aside, the only reason I happened upon the original ticket is because I was looking to report a bug with `--frozen-lockfile` In v1.2.1 where it sometimes fails to exit with an error when a `yarn install` without it actually would edit yarn.lock. I plan to file that soon, but it shouldn’t change the fact that the intended use of it is absolutely CI environments.

**Comment by Daniel15** [comment]
> Scenario: package.json has a remote dependency with a carat for the version
number, making it update to the latest minor symver.  Remote dependency
pushes a new minor version.
> 
> According to the documentation it will exit with a failure if
> --frozen-lockfile is executed.
> This is not helpful in a ci environment because it doesn't make sense to
> fail a build due to a dependency being out of date. 

That's not right. CI will continue to pass, and Yarn will continue to install the version specified in the lockfile, even if a new version comes out. That's the purpose of the lockfile - All of your dependencies are locked to a 'known good' version.

Yarn will not throw an error if a dependency is out of date. It will only throw an error if the lockfile is incompatible with the package.json file (for example, you've added a new package to package.json but haven't run `yarn install`, or you've updated package.json such that the version of the package specified in the lockfile no longer matches the new range specified in the package.json file)

Perhaps the website is unclear?

**Comment by sesopenko** [comment]
> Yarn will not throw an error if a dependency is out of date. It will only throw an error if the lockfile is incompatible with the package.json file (for example, you've added a new package to package.json but haven't run yarn install, or you've updated package.json such that the version of the package specified in the lockfile no longer matches the new range specified in the package.json file)

Then maybe the documentation for --frozen-lockfile needs to be more clear.

> Don’t generate a yarn.lock lockfile and fail if an update is needed.

There is no explanation of what "an update is needed" includes.  Here's a scenario that needs clarification.

packages.json dependency:
`{
  "dependencies": {
    "vue": "^2.2.6",
  }
}`

Resulting lockfile dependency:
`vue@^2.2.6:
  version "2.4.4"
  resolved "https://registry.yarnpkg.com/vue/-/vue-2.4.4.tgz#ea9550b96a71465fd2b8b17b61673b3561861789"`

What if 2.2.7 is released by the vue maintainers?  Will this be considered a needed update and cause --frozen-lockfile to fail?

**Comment by rally25rs** [comment]
> What if 2.4.5 is released by the vue maintainers and no changes are made the lockfile nor packages.json? Will this still be considered a needed update and cause --frozen-lockfile to fail?

Yarn will:

* check package.json, see `vue@^2.2.6`
* map that in the yarn.lock file: `vue@^2.2.6 => 2.4.4`
* install exactly version 2.4.4

The lockfile does not need to be updated, and the CI build will pass.

> Or is it out of date if packages.json is updated to point to ^3.0.0 (newer version than in the lock file) but the lockfile is still as-is?

Yarn will:

* check package.json, see `vue@^3.0.0`
* map that in the yarn.lock file: `vue@^3.0.0` does not have a mapping (only ^2.2.6 does)
* now we need to add yarn.lock file mapping for `vue@^3.0.0`

`--frozen-lockfile` prevents this additional mapping being added, so the CI build fails.

-----

The primary reasons to have CI fail are:

* Someone hand-edited `package.json` but didn't run `yarn install` to sync yarn.lock with those changes.
* Someone used NPM to install or upgrade a package, and yarn.lock doesn't know about it.

That is why the recommendation is to use `--frozen-lockfile`. It basically points to your package.json having changed without a changed yarn.lock being committed too.

-----

Hopefully that makes sense... but overall yeah we could probably make the wording more clear since most people won't know what constitutes a lockfile change.

**Comment by Daniel15** [comment]
@rally25rs's comment covers it. `--frozen-lockfile` will only fail a build if the package.json is inconsistent with the lockfile, so it's highly recommended and should never break a legitimate build.  Feel free to send a pull request updating the wording on the site if you feel like it's unclear :)
