### ISSUE TITLE
[suggestion] don't open new tab for github links in package detail page

### ISSUE THREAD

**Issue by transitive-bullshit** [yarnpkg/website#794]
Yarn's package search is imho the best search engine for the npm registry that exists.

A very common scenario I find myself doing is opening up a number of search result detail pages in different tabs because I want to investigate different related modules and try to find the one I'd like to use. 99% of the time I want to open up the github repo to view the code directly for those results, as that's the quickest way at a glance to see how respectable a potential module is, so I inevitably end up clicking each of the github links on the N package detail pages which opens up N new tabs, then I have to go back and close each of the N yarn package detail pages.

That's not to say that the yarn detail page isn't useful -- it has extremely useful info on it.  I'm just proposing a very simple change to not open up the repo / github link in a new tab.

I'd be very surprised if I were the only one to find the current behavior of `target="_blank"` annoying, though I'm not sure how much visibility this issue will get on here.

Very happy to submit the couple line PR if you agree to make this minor change.

Thanks!

**Comment by Haroenv** [comment]
Hey @transitive-bullshit, thanks for those nice words! I think that might make sense. They were originally added as target blank since there wasn't a detail page yet, but since that's there now, it might not be as obvious anymore to open in a new tab. 

I'll ask around to some other people if they have opinions about it, but it's probably a good idea (it's in Hit if you want to do a PR
