### ISSUE TITLE
New package version not syncing from npmjs.com

### ISSUE THREAD

**Issue by djmitche** [yarnpkg/website#814]
* https://www.npmjs.com/package/console-taskgraph -> 1.1.0
* https://yarnpkg.com/en/package/console-taskgraph -> 1.0.0

These packages have been at different versions for over an hour now.  I can't `yarn upgrade` from another package, since the yarn index appears to be using the same data.

**Comment by djmitche** [comment]
I should add, `yarn upgrade` does find the newer version -- it's just not on the site.

**Comment by Haroenv** [comment]
Hey @djmitche, the reason this was happening was because we did the weekly complete sync. During that period we get new data from every single package, while during the rest of the week we watch for changes. This process takes 12-20h due to the amount of data necessary to fetch. 

Thanks for catching it!
