### ISSUE TITLE
How do you get the readme to render on a project page?

### ISSUE THREAD

**Issue by mitchellsimoens** [yarnpkg/website#919]
Hi,

I have a monorepo (using lerna) and a published package shows the readme from the root directory, not the readme that is published with (or the `homepage` property in the `package.json` that is published with). Over on npmjs.com the proper readme is displayed. See the two differences:

[yarn project page](https://yarnpkg.com/en/package/@graphidocs/docs)
[npm project page](https://www.npmjs.com/package/@graphidocs/docs)

Yarn's version shows the root [readme](https://github.com/GraphiDocsOrg/docs/blob/master/README.md) where as npm's version shows the proper nested [readme](https://github.com/GraphiDocsOrg/docs/blob/master/packages/docs/README.md). I have the `homepage` in the `package.json` set also: https://github.com/GraphiDocsOrg/docs/blob/master/packages/docs/package.json#L51

How to get yarn to show the correct readme?

Also, I had some deployment issues moving to a monorepo so I had to unpublish some versions as I tested it out. Yarn still shows those versions (1.0.3 for example) but npm does not. How to get those unpublished versions removed from yarn?

**Comment by Daniel15** [comment]
cc @Haroenv

**Comment by Haroenv** [comment]
Ill check out what’s happening next week. This logic is quite complicated and in a closed source part of npm unfortunately.

**Comment by Haroenv** [comment]
In this case npm's api returned an empty string, so we fall back to the root readme, since we have the GitHub repo. The code for that is here:

https://github.com/yarnpkg/website/blob/c864b2da2e0af2ea10db18e284ec5650867a6547/js/src/lib/Details/index.js#L122-L131

http://registry.npmjs.org/@graphidocs/docs

```json5
{
  // other things
  license: "MIT",
  readme: "",
  readmeFilename: ""
}
```

I'll close this, since unfortunately this is npm-dependent and something that should be brought up with them.
